### ISSUE TITLE
Command parsing question

### ISSUE THREAD

**Issue by Alex141642** [Utagai/shi#6] opened 2021-10-04 20:58 UTC
Hi, i discovered this project, and i don't know if it is still maintained.

I have a question, i've made a basic test but i wasn't able to call my command. The code is the following:
```rust
    info!("Configure cli functions");
    let mut shell = Shell::new("| ");
    shell.register(parent!(
        "server",
        //"A set of commands to manage the server",
        cmd!(
            "listen",
            "Start listening on the given port",
            |_, _| {commands::listen()}
        ),
        cmd!(
            "unlisten",
            "stop listening",
            |_, _| {commands::unlisten()}
        )
    ))?;
    shell.run()?;
    Ok(())
```

According to the doc, the commands would be:
* server listen
* server unlisten

However the real command is something like:
* server listen listen
* server unlisten unlisten

Is this a bug or do i do things not correctly?
Thanks

**Comment by Utagai** [comment] 2021-10-04 22:22
Hi there. Thanks for trying it out! I'm taking a look at your code snippet now and will report back with what I find!

**Comment by Utagai** [comment] 2021-10-04 22:54
Ah... I found the issue. There's a particularly important [TODO](https://github.com/Utagai/shi/blob/master/src/shell.rs#L172-L177) in the code that I incorrectly ignored when making a change in 360bc2ca.

Reverting that change makes the code work as we'd expect:
```
shi | ./target/debug/examples/issue6
configure cli functions
| helptree
Normal commands
└── server
    ├── listen
    └── unlisten


Builtins
├── help
├── helptree
├── exit
└── history
| server listen
hello world start
start
| server listen foo
hello world start
start
| server unlisten
hello world stopp
stop
| server unlisten foo
hello world stopp
stop
| exit
bye
```

 I'll be pushing the reversion shortly and bumping the version soon so that should unblock you.

Longer term however, I'll have to do two main things:
* Revert this revert and replace it with a longer term solution, which is as the TODO comment says, which is that we should be building this into the parser instead of relying on the recursive `execute()` method on `ParentCommand`'s.
* Add a proper integration test that catches regressions like this. Ideally, this test runs a pre-compiled binary of `shi` and tries running every single command, expecting a particular output. This can probably be done nicely by using `Shell#eval()`.

**Comment by Utagai** [comment] 2021-10-04 23:15
I've bumped `shi` to version 0.1.4. Let me know if this addresses this issue!

**Comment by Alex141642** [comment] 2021-10-05 05:08
Hi @Utagai , Thanks for the quick response and fix.
0.1.5 works as expected, i will use it in my personal project as it look to be well useful (completion ect is pretty good)

Create public issues, i would be happy to contribute! :)
Have a nice day

**Comment by Utagai** [comment] 2021-10-05 16:58
No problem! Thanks for trying it out! Please feel free to file any other issues you run into!

Going to close this issue since it seems like things are fixed for you now!

**Closed by Utagai** 2021-10-05 16:58 UTC
